version: '3'
services:
  eprints:
    image: eprints/eprints:3.4.4
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ./eprints_config:/opt/eprints3/cfg
      - ./eprints_data:/opt/eprints3/archives
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Alh4mdul1ll4hrepository
      MYSQL_DATABASE: eprints_db
      MYSQL_USER: eprints
      MYSQL_PASSWORD: r3p0poliupgr3p0
    volumes:
      - ./mysql_data:/var/lib/mysql
