version: '3'
services:
  eprints:
    image: eprints/eprints
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ./eprints_config:/opt/eprints3/cfg
      - ./eprints_data:/opt/eprints3/archives
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: eprints_db
      MYSQL_USER: eprints_user
      MYSQL_PASSWORD: eprints_password
    volumes:
      - ./mysql_data:/var/lib/mysql
